id: AFD4AC230
base_file: f4871.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:36:28.832436
  last_modified_at: 2022-06-17 11:36:28.832439
