id: AFD4AC230
base_file: fB57E.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:36:28.852747
  last_modified_at: 2022-06-17 11:36:28.852750
