id: AFD4AC230
base_file: fDC55.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:36:28.859486
  last_modified_at: 2022-06-17 11:36:28.859489
