id: AFD4AC230
base_file: f3C8D.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - it
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:36:28.828960
  last_modified_at: 2022-06-17 11:36:28.828962
