id: AFD4AC230
base_file: f302B.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:36:28.827200
  last_modified_at: 2022-06-17 11:36:28.827202
