id: AFD4AC230
base_file: f2DEE.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:36:28.824453
  last_modified_at: 2022-06-17 11:36:28.824458
