id: AFD4AC230
base_file: f7729.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:36:28.836964
  last_modified_at: 2022-06-17 11:36:28.836967
