id: AFD4AC230
base_file: f77A8.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 11:36:28.838307
  last_modified_at: 2022-06-17 11:36:28.838311
